name: dart_reto2
description: api connection test reto2.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dartz: ^0.10.1
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
